apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80          # Service ka port (browser ke liye)
      targetPort: 80    # Pod ke andar Nginx ka port
      nodePort: 30082   # Fixed NodePort (30000–32767 range me hona chahiye)

