apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  default.conf: |
    server {
      listen 80;

      resolver 10.96.0.10 valid=10s;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api/users {
        proxy_pass http://user-service.default.svc.cluster.local:5000/users;
      }

      location /api/products {
        proxy_pass http://product-service.default.svc.cluster.local:5001/products;
      }

      location /api/orders {
        proxy_pass http://order-service.default.svc.cluster.local:5002/orders;
      }
    }

